package templates

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type ProjectOptions struct {
	Name        string
	ServiceName string
	Replace     string
	DB          string
	Cache       string
	MQ          string
	Registry    string
	Tracing     string
}

func GenerateProject(root string, opts ProjectOptions) error {
	if opts.Name == "" {
		return fmt.Errorf("project name is required")
	}
	if opts.DB == "" {
		opts.DB = "noop"
	}
	if opts.Cache == "" {
		opts.Cache = "memory"
	}
	if opts.MQ == "" {
		opts.MQ = "memory"
	}
	if opts.Registry == "" {
		opts.Registry = "memory"
	}
	if opts.Tracing == "" {
		opts.Tracing = "noop"
	}
	if opts.ServiceName == "" {
		opts.ServiceName = "example-service"
	}
	base := filepath.Join(root, opts.Name)
	if opts.Replace == "" {
		opts.Replace = detectLocalReplace(root, base)
	}
	files := map[string]string{
		"go.mod":                               projectGoMod,
		"buf.yaml":                             bufYaml,
		"buf.gen.yaml":                         bufGenYaml,
		"README.md":                            projectReadme,
		"config/base.yaml":                     baseConfig,
		"gateway/cmd/main.go":                  gatewayMain,
		"services/example-service/cmd/main.go": serviceMain,
		"api/proto/example/v1/example.proto":   exampleProto,
		"services/example-service/internal/README.md": serviceInternalReadme,
	}
	for path, body := range files {
		if err := writeTemplate(filepath.Join(base, path), body, opts); err != nil {
			return err
		}
	}
	return nil
}

func GenerateService(root, name string) error {
	if name == "" {
		return fmt.Errorf("service name is required")
	}
	data := struct {
		Name        string
		ServiceName string
		ProtoName   string
	}{
		Name:        name,
		ServiceName: name,
		ProtoName:   strings.ReplaceAll(name, "-", "_"),
	}
	files := map[string]string{
		filepath.Join("api/proto", name, "v1", name+".proto"): serviceProto,
		filepath.Join("services", name, "cmd/main.go"):        serviceMain,
		filepath.Join("services", name, "internal/README.md"): serviceInternalReadme,
	}
	for path, body := range files {
		if err := writeTemplate(filepath.Join(root, path), body, data); err != nil {
			return err
		}
	}
	return nil
}

func writeTemplate(path, body string, data any) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tpl, err := template.New(filepath.Base(path)).Parse(body)
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, data); err != nil {
		return err
	}
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

func detectLocalReplace(root, projectDir string) string {
	data, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return ""
	}
	if !strings.Contains(string(data), "module github.com/svcforge/service-forge") {
		return ""
	}
	rel, err := filepath.Rel(projectDir, root)
	if err != nil {
		return root
	}
	return rel
}

const projectGoMod = `module {{ .Name }}

go 1.23

require github.com/svcforge/service-forge v0.0.0
{{ if .Replace }}
replace github.com/svcforge/service-forge => {{ .Replace }}
{{ end }}
`

const bufYaml = `version: v2
modules:
  - path: api/proto
`

const bufGenYaml = `version: v2
plugins:
  - remote: buf.build/protocolbuffers/go
    out: api/gen/go
    opt: paths=source_relative
  - remote: buf.build/grpc/go
    out: api/gen/go
    opt: paths=source_relative
`

const projectReadme = `# {{ .Name }}

Generated by Service Forge.

## Architecture

- Gateway exposes REST/JSON.
- Services expose gRPC only.
- Business code depends on ports, while adapters provide Redis/Postgres/RabbitMQ/Consul/etc.

## Local start

` + "```bash" + `
go mod tidy
go run ./gateway/cmd
go run ./services/example-service/cmd
` + "```" + `
`

const baseConfig = `app:
  name: {{ .Name }}
  version: v0.1.0
  env: development
  debug: true

gateway:
  listen_ip: 0.0.0.0
  port: 8080
  disable_startup_message: true
  # Built-in plugins are off until listed here. They run in config order.
  # Available: recovery, access_log, cors, rate_limit, api_key, jwt, metrics.
  # plugins:
  #   - name: recovery
  #   - name: access_log
  #   - name: rate_limit
  #     config:
  #       max: 100
  #       window: 1m
  #   - name: metrics
  routes:
    # Configure REST/JSON to gRPC proxy routes here.
    # For local multi-process development with memory registry, use target.
    # With consul or another shared registry, use service instead.
    # - name: example-ping
    #   method: POST
    #   path: /api/v1/ping
    #   target: 127.0.0.1:9000
    #   rpc: /example.v1.ExampleService/Ping
    #   pool_size: 1
    #   timeout: 3s

log:
  format: text
  level: info
  module_lifecycle: false

grpc:
  listen_ip: 0.0.0.0
  port: 9000

runtime:
  components:
    - name: store
      provider: {{ .DB }}
    - name: cache
      provider: {{ .Cache }}
    - name: eventbus
      provider: {{ .MQ }}
    - name: registry
      provider: {{ .Registry }}
    - name: tracing
      provider: {{ .Tracing }}

modules:
  postgres:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    database: {{ .Name }}
    sslmode: disable
  redis:
    addr: localhost:6379
  rabbitmq:
    url: amqp://guest:guest@localhost:5672/
    exchange: events
  consul:
    address: localhost:8500
`

const gatewayMain = `package main

import (
	"context"
	"log"

	"github.com/svcforge/service-forge/adapters"
	"github.com/svcforge/service-forge/core/app"
	"github.com/svcforge/service-forge/core/config"
	"github.com/svcforge/service-forge/transport/gateway"
	"github.com/gofiber/fiber/v2"
)

func main() {
	bundle, err := config.Load[struct{}](config.LoadOptions{
		ConfigDir:   "config",
		ServiceName: "{{ .Name }}",
		EnableLocal: true,
	})
	if err != nil {
		log.Fatal(err)
	}

	gw := gateway.New(func(router *fiber.App, gw *gateway.Gateway) {
		router.Get("/api/v1/ping", gw.Handle(func(ctx context.Context, c *fiber.Ctx) (any, error) {
			return fiber.Map{"message": "pong"}, nil
		}))
	})

	mods, err := adapters.DefaultCatalog().Build(bundle.Core.Runtime.Components)
	if err != nil {
		log.Fatal(err)
	}
	mods = append(mods, gw)

	application := app.New(bundle.Core, app.WithModules(mods...))
	if err := application.Run(context.Background()); err != nil {
		log.Fatal(err)
	}
}
`

const serviceMain = `package main

import (
	"context"
	"log"

	"github.com/svcforge/service-forge/adapters"
	"github.com/svcforge/service-forge/core/app"
	"github.com/svcforge/service-forge/core/config"
	"github.com/svcforge/service-forge/transport/grpcserver"
)

func main() {
	bundle, err := config.Load[struct{}](config.LoadOptions{
		ConfigDir:   "config",
		ServiceName: "{{ .ServiceName }}",
		EnableLocal: true,
	})
	if err != nil {
		log.Fatal(err)
	}

	mods, err := adapters.DefaultCatalog().Build(bundle.Core.Runtime.Components)
	if err != nil {
		log.Fatal(err)
	}
	mods = append(mods, grpcserver.NewModule(
		// Register generated gRPC servers here, for example:
		// examplev1.RegisterExampleServiceServer,
	))

	application := app.New(bundle.Core, app.WithModules(mods...))
	if err := application.Run(context.Background()); err != nil {
		log.Fatal(err)
	}
}
`

const exampleProto = `syntax = "proto3";

package example.v1;

option go_package = "{{ .Name }}/api/gen/go/example/v1;examplev1";

service ExampleService {
  rpc Ping(PingRequest) returns (PingResponse);
}

message PingRequest {
  string message = 1;
}

message PingResponse {
  string message = 1;
}
`

const serviceProto = `syntax = "proto3";

package {{ .ProtoName }}.v1;

option go_package = "api/gen/go/{{ .Name }}/v1;{{ .ProtoName }}v1";

service {{ .ProtoName }}Service {
  rpc Health(HealthRequest) returns (HealthResponse);
}

message HealthRequest {}

message HealthResponse {
  string status = 1;
}
`

const serviceInternalReadme = `# Internal service layout

Recommended layout:

- handler/rpc: generated gRPC server implementation
- service: business logic depending on ports
- repository: storage implementation details
- model: persistence model
- setup: adapter wiring
`
